# Generated by Django 5.0.6 on 2024-06-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='cursos', to='main.estudiante'),
        ),
    ]
